version: '3'
services:
    flask:
        image: flask
        build:
            context: .
            dockerfile: scripts/dockerfile-flask
        ports:
            - 5000:5000
        environment:
            - ENVIRONMENT=docker
